/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 8N Films Official (https://sketchfab.com/8nfilms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/banana-skin-in-substance-painter-b0d1aa58ef3a442e929363e8422641c7
Title: Banana Skin in Substance Painter
*/
import { useGLTF } from '@react-three/drei'
import bananaScene from '../3d/banana-model.glb';

export default function BananaModel({ ...props }: BananaModelProps) {
  const { nodes, materials } = useGLTF(bananaScene);

  return (
    <group
      {...props}
      dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.banana2}
          rotation={[Math.PI / 2, 0, 0]}
          onBeforeRender={() => {
            if (materials.banana2 && materials.banana2.opacity < 1) {
              materials.banana2.opacity += 0.01;
            }
          }}
          onUpdate={() => {
            if (materials.banana2) {
              materials.banana2.transparent = true;
              materials.banana2.opacity = 0
            }
          }}
        />
      </group>
    </group>
  );
}

interface BananaModelProps {
  scale: [x: number, y: number, z: number];
}